config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/contact',   to: 'pages#contact'
  get '/about',     to: 'pages#about'
  get 'classes-list', to: 'pages#classes-list'
  get 'classes-detail', to: 'pages#classes-detail'
  get 'style-guide', to: 'pages#style-guide'
  get 'testimonial', to: 'pages#testimonial'
  get '/pricing', to: 'pages#pricing'
  get 'blog-default', to: 'pages#blog-default'
  get 'blog-single', to: 'pages#blog-single'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  resources :categories, only: [:show]
  get 'password_resets/new'
  get 'password_resets/edit'


  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    root :to => '/pages#index'
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages  #/admin/pages
    resources :categories
    resources :users, only: [:index, :destroy]

  end
  
  Page.where.not("slug" => nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end
  
end

app/views/admin/pages/_form.html.erb
<%= form_for [ "admin", @page ] do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:" %>
      </h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </p>
    <h3>Custom fields</h3>
  <%= f.fields_for :fields do |c| %>
    <p>
      <%= c.label :value, c.object.field_definition.key %>
      <%= c.text_field :value, class: "form-control" %>
      <%= c.hidden_field :field_definition_id %>
    </p>
  <% end %>
  <p>
    <%= f.label :body %>
    <%= f.cktext_area :body %>
  </p>
  <p>
    <%= f.label :slug %>
    <%= f.text_field :slug, class: "form-control" %>
  </p>
  
    <p>
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.map { |category| [category.name, category.id]}, class: "form-control" %>
  </p>

    <p>
    <%= f.hidden_field :type_id %>
  </p>

  <p>
    <%= f.submit 'Save' %>
  </p>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_page_path(@page) %>
|
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Web Pages</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td>
          <%= link_to page.title, edit_admin_page_path(page) %>
        </td>
        <td>
          <%= truncate page.body, length: 100 %>
        </td>
        <td>
          <code>
            <%= url_for_page page %>
          </code>
        </td>
        <td>
          <%= link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <% Type.all.each do |type| %>
  <%= link_to "New #{type.name}", new_admin_page_path(type: type.name), class: "btn btn-primary" %>
  <% end %>
</p>

app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<h1>
  <%= @page.title %>
</h1>
  <%= simple_format @page.body %>
  <%= link_to 'Edit', edit_admin_page_path(@page) %>
  |
  <%= link_to 'Back', admin_pages_path %>