config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/contact',   to: 'pages#contact'
  get '/about',     to: 'pages#about'
  get 'classes-list', to: 'pages#classes-list'
  get 'classes-detail', to: 'pages#classes-detail'
  get 'style-guide', to: 'pages#style-guide'
  get 'testimonial', to: 'pages#testimonial'
  get '/pricing', to: 'pages#pricing'
  get 'blog-default', to: 'pages#blog-default'
  get 'blog-single', to: 'pages#blog-single'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  resources :categories, only: [:show]
  get 'password_resets/new'
  get 'password_resets/edit'


  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    root :to => '/pages#index'
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages  #/admin/pages
    resources :categories
    resources :users, only: [:index, :destroy]

  end
  
  Page.where.not("slug" => nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :pages
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
  layout 'admin_application'
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
       @category = Category.includes(:pages).find params[:id]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [ "admin", @category ] do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:" %>
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>


<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td>
          <%= category.name %>
        </td>
        <td>
          <%= link_to 'Show', admin_category_path(category) %>
        </td>
        <td>
          <%= link_to 'Edit', edit_admin_category_path(category) %>
        </td>
        <td>
          <%= link_to 'Destroy', admin_category_path(category), :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'New Category', new_admin_category_path %>
</p>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>