config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/contact',   to: 'pages#contact'
  get '/about',     to: 'pages#about'
  get 'classes-list', to: 'pages#classes-list'
  get 'classes-detail', to: 'pages#classes-detail'
  get 'style-guide', to: 'pages#style-guide'
  get 'testimonial', to: 'pages#testimonial'
  get '/pricing', to: 'pages#pricing'
  get 'blog-default', to: 'pages#blog-default'
  get 'blog-single', to: 'pages#blog-single'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  resources :categories, only: [:show]
  get 'password_resets/new'
  get 'password_resets/edit'


  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    root :to => '/pages#index'
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages  #/admin/pages
    resources :categories
    resources :users, only: [:index, :destroy]

  end
  
  Page.where.not("slug" => nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 include SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
     # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Resume"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
  
  def url_for_page page
    if page.slug.present?
      page.slug
    else
      "pages/#{page.id}"
    end
  end
  
  def url_for_menu_item menu_item
    if menu_item.url.match /:\/\// # http://, ftp://, etc.
       menu_item.url
    else
      root_path + menu_item.url
    end
  end

end

app/views/application/_admin_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display
    -->
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#main-nav" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Admin Panel", admin_pages_url, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling
    -->
    <div class="collapse navbar-collapse" id="main-nav">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Content", admin_pages_path %>
        </li>
        <li>
          <%= link_to "Categories", admin_categories_path %>
        </li>
        <li>
          <%= link_to "Menus", admin_menus_path %>
        </li>
        <li>
          <%= link_to "Types", admin_types_path %>
        </li>
        <li>
         <%= link_to "Users", admin_users_path %>
         </li>
      </ul>
    </div>
  </div>
</nav>