config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/contact',   to: 'pages#contact'
  get '/about',     to: 'pages#about'
  get 'classes-list', to: 'pages#classes-list'
  get 'classes-detail', to: 'pages#classes-detail'
  get 'style-guide', to: 'pages#style-guide'
  get 'testimonial', to: 'pages#testimonial'
  get '/pricing', to: 'pages#pricing'
  get 'blog-default', to: 'pages#blog-default'
  get 'blog-single', to: 'pages#blog-single'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages, only: [:show]
  resources :categories, only: [:show]
  get 'password_resets/new'
  get 'password_resets/edit'


  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do
    root :to => '/pages#index'
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages  #/admin/pages
    resources :categories
    resources :users, only: [:index, :destroy]

  end
  
  Page.where.not("slug" => nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end
  
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
      <small>
         Group Project by <a href="https://www.linkedin.com/in/julie-anne-glennon-18783157">Julie-Anne Glennon</a>
         <a href="https://www.linkedin.com/in/haider-bari-245bba108">Haider Bari</a>
          Student Numbers 2864184 | 2835713
      </small>
       
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Contact",   contact_path %></li>
            <li><% link_to "Pricing", pricing_path %></li>
          </ul>
        </nav>
      </div>
    </footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Group Project", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Contact",  contact_path %></li>
            <% if logged_in? && current_user.admin? %>

            <li><%= link_to "Admin", users_path %></li>
             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
             
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
             <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>
 

app/views/layouts/_rails_default.html.erb
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta/>
    <title>Admin Panel</title>
    <%= stylesheet_link_tag    'scaffolds', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'scaffolds', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "admin_nav" %>
    <div class="container">
      <%= content_tag :div, notice, class: "flash bg-success" if notice %>
      <%= content_tag :div, alert, class: "flash bg-danger" if alert %>
      <%= yield  %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  </head>
<body>
  <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>